services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    expose:
      - "${PORT}"
    ports:
      - "8081:${PORT}"

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    expose:
      - "${PORT}"
    ports:
      - "8082:${PORT}"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app_blue
      - app_green
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      ACTIVE_POOL: ${ACTIVE_POOL}
      PORT: ${PORT}
    restart: always
